# Generated by Django 4.2.9 on 2024-10-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeliveryLocations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("Abia", "Abia"),
                            ("Adamawa", "Adamawa"),
                            ("Akwa Ibom", "Akwa Ibom"),
                            ("Anambra", "Anambra"),
                            ("Bauchi", "Bauchi"),
                            ("Bayelsa", "Bayelsa"),
                            ("Benue", "Benue"),
                            ("Borno", "Borno"),
                            ("Cross River", "Cross River"),
                            ("Delta", "Delta"),
                            ("Ebonyi", "Ebonyi"),
                            ("Edo", "Edo"),
                            ("Ekiti", "Ekiti"),
                            ("Enugu", "Enugu"),
                            ("Gombe", "Gombe"),
                            ("Imo", "Imo"),
                            ("Jigawa", "Jigawa"),
                            ("Kaduna", "Kaduna"),
                            ("Kano", "Kano"),
                            ("Katsina", "Katsina"),
                            ("Kebbi", "Kebbi"),
                            ("Kogi", "Kogi"),
                            ("Kwara", "Kwara"),
                            ("Lagos", "Lagos"),
                            ("Nasarawa", "Nasarawa"),
                            ("Niger", "Niger"),
                            ("Ogun", "Ogun"),
                            ("Ondo", "Ondo"),
                            ("Osun", "Osun"),
                            ("Oyo", "Oyo"),
                            ("Plateau", "Plateau"),
                            ("Rivers", "Rivers"),
                            ("Sokoto", "Sokoto"),
                            ("Taraba", "Taraba"),
                            ("Yobe", "Yobe"),
                            ("Zamfara", "Zamfara"),
                            ("FCT", "Federal Capital Territory FCT"),
                        ],
                        max_length=50,
                    ),
                ),
                ("town_name", models.CharField(default="", max_length=50)),
                ("location", models.CharField(blank=True, max_length=50, null=True)),
                ("city_name", models.CharField(default="", max_length=50)),
                (
                    "delivery_cost",
                    models.DecimalField(decimal_places=2, default=1000, max_digits=10),
                ),
                ("delivery_days", models.IntegerField(default=2)),
            ],
        ),
    ]
