# Generated by Django 4.2.9 on 2024-10-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="facebook_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="instagram",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="twiter_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="youtube_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
