# Generated by Django 4.2.9 on 2024-10-25 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0002_sitesettings_facebook_link_sitesettings_instagram_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="site_name",
            field=models.CharField(default="My Site", max_length=100),
        ),
    ]
