# Generated by Django 4.2.9 on 2024-10-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0003_sitesettings_site_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="site_logo/"),
        ),
    ]
